services:
  - type: web
    name: fu-donation-group-12
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm --prefix ../frontend install && npm --prefix ../frontend run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
